<?php 
function roots_custom_form_commerce_checkout_form_roots_reg_children_info_alter(&$form, &$form_state, $form_id) {
  $form['roots_reg_children_pane']['redhen_contact_email']['#access'] = FALSE;
}
function roots_custom_form_commerce_checkout_form_checkout_alter(&$form, &$form_state, $form_id) {
  $form['commerce_payment']['payment_details']['#suffix'] = '<p>If you are not paying full price right now please check this so we can charge your card for the remaining balance.</p></div>';
}

/**
 * Implements hook_commerce_checkout_pane_info().
 */
function roots_custom_commerce_checkout_pane_info() {
  $checkout_panes = array();

  $checkout_panes['roots_custom_message_pane'] = array(
    'title' => t('Terms and Conditions'),
    'base' => 'commerce_message_pane', // <== That's all that is needed
    'enabled' => TRUE,
  );

  return $checkout_panes;
}

function roots_custom_menu_alter(&$items){
  $items['user/register']['title'] = 'New student registration';
  $items['user/login']['title'] = 'Returning student registration';
  $items['user/password']['type'] = MENU_CALLBACK;
}

function roots_custom_form_user_register_form_alter(&$form, $form_id){
  drupal_set_title('Course Registration');
  $form['instructions'] = array(
    '#markup' => t('<p class="form-instructions">Enter your own name (even if you\'re registering your child).</p>'),
    '#weight' => -21,
  );
  $form['redhen_contact']['#weight'] = -20;
  $form['actions']['submit']['#value'] = 'Begin registration';
}
function roots_custom_form_user_login_alter(&$form, $form_id){
  drupal_set_title('Course Registration');
  $form['instructions'] = array(
    '#markup' => t('<p class="form-instructions">If you\'ve signed up on our website before you can register now by logging in here.</p>'),
    '#weight' => -10,
  );
  //$form['password-reset'] = array(
  //  '#markup' => t('<p class="password-reset"><a href="/user/password" title="Login without password">Register without your password</a></p>'),
  $form['actions']['submit']['#value'] = 'Save';
  //  '#weight' => 1,
  //);
  $form['pass']['#description'] = 'If you forgot your password you can <a href="/user/password" title="Login without password">register without it here</a>.';
  $form['actions']['submit']['#value'] = 'Begin registration';
}
function roots_custom_form_user_pass_alter(&$form, $form_id) {
  drupal_set_title('Course Registration');
  $form['instructions'] = array(
    '#markup' => t('<p class="form-instructions">Our robot will email you a link so you can log in and register.  After you register you can reset your password if you want.</p>'),
    '#weight' => -10,
  );
  unset($form['name']['#description']);
  $form['actions']['submit']['#value'] = 'Email me a login link';
}

function roots_custom_form_program_registration_node_form_alter(&$form, $form_id) {
  $form['author']['#weight'] = -10;
  $form['author']['#title'] = 'Registrant Contact';
  $form['author']['name']['#title'] = 'Email address of the existing website user to email for correspondences';
  $form['author']['name']['#default_value'] = '';
  $form['author']['name']['#required'] = 1;
  $form['actions']['submit']['#value'] = 'Save';
  unset($form['author']['name']['#description'], $form['author']['date']);
  unset($form['revision_information'], $form['metatags'], $form['path'], $form['menu'], $form['options']);
  unset($form['actions']['preview'], $form['actions']['draft']);
}
